site_name: Guide to Advanced LLM Techniques
site_url: https://example.com
nav:
  - Home: index.md
  - Aulas:
      - Aula 1: 01_langchain_structured_outputs.ipynb
      - Aula 2: 02_prompting.ipynb
      - Aula 3: 03_llm_ensemble.ipynb
      - Aula 4: 04_fine_tuning.ipynb
theme:
  name: material
plugins:
  - search
  - mkdocs-jupyter
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
